"""empty message

Revision ID: e2919f91d570
Revises: 020e1177616e
Create Date: 2020-12-31 10:58:50.454789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2919f91d570'
down_revision = '020e1177616e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_artis_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'artis_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artis_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_artis_id_fkey', 'Show', 'Artist', ['artis_id'], ['id'])
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
